/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;


import clases.FondoEscritorio;
import static java.awt.image.ImageObserver.HEIGHT;
import org.jpl7.Query;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Escritorio extends javax.swing.JFrame {

    /**
     * Creates new form Primera
     */
    
    public Escritorio() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("SISTEMA DE DIAGNÓSTICO DE PLAGAS DE CAFETO");
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/hospital.png")).getImage());
        
        this.jButtonBroca.setLocation(-430, 20);
        this.jButtonCochinillaAerea.setLocation(-430, 218);
        this.jButtonBarrenador.setLocation(-430, 418);
        
        this.jButtonMinador.setLocation(-430, 20);
        this.jButtonGallinaCiega.setLocation(-430, 218);
        this.jButtonGrillo.setLocation(-430, 418);
        
        this.jButtonCochinillaRaiz.setLocation(-430, 20);
        this.jButtonArañaRoja.setLocation(-430, 218);
        this.jButtonPulgones.setLocation(-430, 418);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCabecera = new javax.swing.JPanel();
        jButtonMenu = new rsbuttom.RSButtonMetro();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDesktopPane = new clases.FondoEscritorio();
        jPanelOpciones = new javax.swing.JPanel();
        ButtonSalir = new rsbuttom.RSButtonMetro();
        ButtonDiagnosticar = new rsbuttom.RSButtonMetro();
        ButtonPlagas = new rsbuttom.RSButtonMetro();
        ButtonAboutUs = new rsbuttom.RSButtonMetro();
        jButtonCochinillaRaiz = new javax.swing.JButton();
        jButtonBroca = new javax.swing.JButton();
        jButtonMinador = new javax.swing.JButton();
        jButtonCochinillaAerea = new javax.swing.JButton();
        jButtonGallinaCiega = new javax.swing.JButton();
        jButtonArañaRoja = new javax.swing.JButton();
        jButtonBarrenador = new javax.swing.JButton();
        jButtonGrillo = new javax.swing.JButton();
        jButtonPulgones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelCabecera.setBackground(new java.awt.Color(153, 153, 153));

        jButtonMenu.setBackground(new java.awt.Color(153, 153, 153));
        jButtonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.png"))); // NOI18N
        jButtonMenu.setText("MENÚ");
        jButtonMenu.setBorderPainted(false);
        jButtonMenu.setColorBorde(null);
        jButtonMenu.setColorHover(new java.awt.Color(0, 153, 204));
        jButtonMenu.setColorNormal(new java.awt.Color(153, 153, 153));
        jButtonMenu.setColorTextNormal(new java.awt.Color(51, 51, 51));
        jButtonMenu.setFocusPainted(false);
        jButtonMenu.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 30)); // NOI18N
        jButtonMenu.setIconTextGap(15);
        jButtonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMenuMouseClicked(evt);
            }
        });
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hospital.png"))); // NOI18N
        jLabel1.setToolTipText("Sobre Nosotros");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Vivaldi", 1, 60)); // NOI18N
        jLabel2.setText("Sistema Experto");

        javax.swing.GroupLayout jPanelCabeceraLayout = new javax.swing.GroupLayout(jPanelCabecera);
        jPanelCabecera.setLayout(jPanelCabeceraLayout);
        jPanelCabeceraLayout.setHorizontalGroup(
            jPanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanelCabeceraLayout.setVerticalGroup(
            jPanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCabeceraLayout.createSequentialGroup()
                .addGroup(jPanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCabeceraLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCabeceraLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButtonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanelOpciones.setBackground(new java.awt.Color(255, 153, 51));

        ButtonSalir.setBackground(new java.awt.Color(255, 153, 51));
        ButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        ButtonSalir.setToolTipText("Salir");
        ButtonSalir.setColorHover(new java.awt.Color(0, 153, 153));
        ButtonSalir.setColorNormal(new java.awt.Color(255, 153, 51));
        ButtonSalir.setColorTextNormal(new java.awt.Color(0, 0, 0));
        ButtonSalir.setFocusPainted(false);
        ButtonSalir.setFont(new java.awt.Font("Haettenschweiler", 0, 30)); // NOI18N
        ButtonSalir.setIconTextGap(15);
        ButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonSalirMouseClicked(evt);
            }
        });
        ButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalirActionPerformed(evt);
            }
        });

        ButtonDiagnosticar.setBackground(new java.awt.Color(255, 153, 51));
        ButtonDiagnosticar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/doctor.png"))); // NOI18N
        ButtonDiagnosticar.setToolTipText("Diagnosticar mi Cafeto");
        ButtonDiagnosticar.setColorHover(new java.awt.Color(0, 153, 153));
        ButtonDiagnosticar.setColorNormal(new java.awt.Color(255, 153, 51));
        ButtonDiagnosticar.setColorTextNormal(new java.awt.Color(0, 0, 0));
        ButtonDiagnosticar.setFocusPainted(false);
        ButtonDiagnosticar.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        ButtonDiagnosticar.setIconTextGap(15);
        ButtonDiagnosticar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonDiagnosticarMouseClicked(evt);
            }
        });
        ButtonDiagnosticar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDiagnosticarActionPerformed(evt);
            }
        });

        ButtonPlagas.setBackground(new java.awt.Color(255, 153, 51));
        ButtonPlagas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ladybug.png"))); // NOI18N
        ButtonPlagas.setToolTipText("Información sobre las Plagas");
        ButtonPlagas.setColorHover(new java.awt.Color(0, 153, 153));
        ButtonPlagas.setColorNormal(new java.awt.Color(255, 153, 51));
        ButtonPlagas.setColorTextNormal(new java.awt.Color(0, 0, 0));
        ButtonPlagas.setFocusPainted(false);
        ButtonPlagas.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        ButtonPlagas.setIconTextGap(15);
        ButtonPlagas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonPlagasMouseClicked(evt);
            }
        });
        ButtonPlagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPlagasActionPerformed(evt);
            }
        });

        ButtonAboutUs.setBackground(new java.awt.Color(255, 153, 51));
        ButtonAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/equipo.png"))); // NOI18N
        ButtonAboutUs.setToolTipText("Acerca de Nosotros");
        ButtonAboutUs.setColorHover(new java.awt.Color(0, 153, 153));
        ButtonAboutUs.setColorNormal(new java.awt.Color(255, 153, 51));
        ButtonAboutUs.setColorTextNormal(new java.awt.Color(0, 0, 0));
        ButtonAboutUs.setFocusPainted(false);
        ButtonAboutUs.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        ButtonAboutUs.setIconTextGap(15);
        ButtonAboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonAboutUsMouseClicked(evt);
            }
        });
        ButtonAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAboutUsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOpcionesLayout = new javax.swing.GroupLayout(jPanelOpciones);
        jPanelOpciones.setLayout(jPanelOpcionesLayout);
        jPanelOpcionesLayout.setHorizontalGroup(
            jPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonPlagas, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(ButtonDiagnosticar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(ButtonAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(ButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelOpcionesLayout.setVerticalGroup(
            jPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(ButtonPlagas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(ButtonDiagnosticar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(ButtonAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(ButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jDesktopPane.add(jPanelOpciones);
        jPanelOpciones.setBounds(0, 0, 150, 650);

        jButtonCochinillaRaiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cochinillaRaiz.jpg"))); // NOI18N
        jButtonCochinillaRaiz.setToolTipText("Cochinilla de la Raíz");
        jButtonCochinillaRaiz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCochinillaRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCochinillaRaizActionPerformed(evt);
            }
        });
        jDesktopPane.add(jButtonCochinillaRaiz);
        jButtonCochinillaRaiz.setBounds(940, 20, 360, 174);

        jButtonBroca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/broca-de-cafe.jpg"))); // NOI18N
        jButtonBroca.setToolTipText("Boca del Cafè");
        jButtonBroca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBroca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrocaActionPerformed(evt);
            }
        });
        jDesktopPane.add(jButtonBroca);
        jButtonBroca.setBounds(100, 20, 360, 174);

        jButtonMinador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minador.jpg"))); // NOI18N
        jButtonMinador.setToolTipText("Minador de la Hoja");
        jButtonMinador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinadorActionPerformed(evt);
            }
        });
        jDesktopPane.add(jButtonMinador);
        jButtonMinador.setBounds(520, 20, 360, 174);

        jButtonCochinillaAerea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cochinillaAerea.jpg"))); // NOI18N
        jButtonCochinillaAerea.setToolTipText("Cochinilla Aérea");
        jButtonCochinillaAerea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCochinillaAerea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCochinillaAereaActionPerformed(evt);
            }
        });
        jDesktopPane.add(jButtonCochinillaAerea);
        jButtonCochinillaAerea.setBounds(100, 220, 360, 174);

        jButtonGallinaCiega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gallinaCiega.jpg"))); // NOI18N
        jButtonGallinaCiega.setToolTipText("Gallina Ciega");
        jButtonGallinaCiega.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGallinaCiega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGallinaCiegaActionPerformed(evt);
            }
        });
        jDesktopPane.add(jButtonGallinaCiega);
        jButtonGallinaCiega.setBounds(520, 220, 360, 174);

        jButtonArañaRoja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arañaRoja.jpg"))); // NOI18N
        jButtonArañaRoja.setToolTipText("Araña Roja");
        jButtonArañaRoja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonArañaRoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArañaRojaActionPerformed(evt);
            }
        });
        jDesktopPane.add(jButtonArañaRoja);
        jButtonArañaRoja.setBounds(940, 220, 360, 174);

        jButtonBarrenador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barrenador.jpg"))); // NOI18N
        jButtonBarrenador.setToolTipText("Barrenador del Tallo");
        jButtonBarrenador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBarrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBarrenadorActionPerformed(evt);
            }
        });
        jDesktopPane.add(jButtonBarrenador);
        jButtonBarrenador.setBounds(100, 420, 360, 174);

        jButtonGrillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/grillo.jpg"))); // NOI18N
        jButtonGrillo.setToolTipText("Grillo del Cafeto");
        jButtonGrillo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGrillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGrilloActionPerformed(evt);
            }
        });
        jDesktopPane.add(jButtonGrillo);
        jButtonGrillo.setBounds(520, 420, 360, 174);

        jButtonPulgones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pulgon.jpg"))); // NOI18N
        jButtonPulgones.setToolTipText("Pulgones");
        jButtonPulgones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPulgones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPulgonesActionPerformed(evt);
            }
        });
        jDesktopPane.add(jButtonPulgones);
        jButtonPulgones.setBounds(940, 420, 360, 174);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane)
                    .addComponent(jPanelCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jDesktopPane))
            .addComponent(jPanelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ((FondoEscritorio) jDesktopPane).setImagen("../imagenes/fondoEscritorio.jpg");
        jPanelCabecera.setSize(jDesktopPane.getWidth(), 100);
        jPanelOpciones.setSize(150, jDesktopPane.getHeight());
        
    }//GEN-LAST:event_formWindowOpened

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jButtonMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenuMouseClicked
        
        int posicionBroca = this.jButtonBroca.getX();
        if(posicionBroca > -1){
            moverPlagas();
        }
                
        moverPanel();
        
    }//GEN-LAST:event_jButtonMenuMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
    }//GEN-LAST:event_jLabel1MouseMoved

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
    }//GEN-LAST:event_jLabel1MouseExited

    private void ButtonAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAboutUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAboutUsActionPerformed

    private void ButtonAboutUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAboutUsMouseClicked

        SobreNosotros sobreNosotros = new SobreNosotros();
        jDesktopPane.add(sobreNosotros);

        int x = ((jDesktopPane.getWidth() - sobreNosotros.getWidth()) / 2);
        int y = ((jDesktopPane.getHeight() - sobreNosotros.getHeight()) / 2);

        sobreNosotros.setLocation(x, y);
        sobreNosotros.setVisible(true);
        moverPanel();

    }//GEN-LAST:event_ButtonAboutUsMouseClicked

    private void ButtonPlagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPlagasActionPerformed
        moverPanel();

        moverPlagas();
    }//GEN-LAST:event_ButtonPlagasActionPerformed

    private void ButtonPlagasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPlagasMouseClicked

    }//GEN-LAST:event_ButtonPlagasMouseClicked

    private void ButtonDiagnosticarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDiagnosticarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonDiagnosticarActionPerformed

    private void ButtonDiagnosticarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonDiagnosticarMouseClicked

        moverPanel();
        
        int continuar = JOptionPane.showConfirmDialog(null, "Una vez iniciado el diagnóstico no podrá interrumpirlo. "
                + "¿Desea continuar?", "¿Desea diagnosticar qué plaga tiene su cafeto?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(continuar == 0) {
            try {
                String conexion = "consult('plagas.pl')";
                Query con = new Query(conexion);
                System.out.println(conexion + " " + (con.hasMoreSolutions() ? "ARCHIVO ENCONTRADO" : "ARCHIVO NO ENCONTRADO"));

                String consulta = "main.";
                Query ejecutar = new Query(consulta);
                if (ejecutar.hasSolution()) {
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Conexión Fallida", HEIGHT);
            }
            moverPlagas();
        }else{
            moverPanel();
        }
    }//GEN-LAST:event_ButtonDiagnosticarMouseClicked

    private void ButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalirActionPerformed

    }//GEN-LAST:event_ButtonSalirActionPerformed

    private void ButtonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_ButtonSalirMouseClicked

    private void jButtonCochinillaRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCochinillaRaizActionPerformed
        
        CochinillaRaiz c = new CochinillaRaiz();
        jDesktopPane.add(c);
        try {
            c.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Escritorio.class.getName()).log(Level.SEVERE, null, ex);
        }
        c.setVisible(true);
        
    }//GEN-LAST:event_jButtonCochinillaRaizActionPerformed

    private void jButtonArañaRojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArañaRojaActionPerformed
        
        Arana a = new Arana();
        jDesktopPane.add(a);
        try {
            a.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Escritorio.class.getName()).log(Level.SEVERE, null, ex);
        }
        a.setVisible(true);
        
    }//GEN-LAST:event_jButtonArañaRojaActionPerformed

    private void jButtonPulgonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPulgonesActionPerformed
        
        Pulgon p = new Pulgon();
        jDesktopPane.add(p);
        try {
            p.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Escritorio.class.getName()).log(Level.SEVERE, null, ex);
        }
        p.setVisible(true);
        
    }//GEN-LAST:event_jButtonPulgonesActionPerformed

    private void jButtonBrocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrocaActionPerformed
        
        Broca broca = new Broca();
        jDesktopPane.add(broca);
        try {
            broca.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Escritorio.class.getName()).log(Level.SEVERE, null, ex);
        }
        broca.setVisible(true);

    }//GEN-LAST:event_jButtonBrocaActionPerformed

    private void jButtonMinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinadorActionPerformed
        
        Minador minador = new Minador();
        jDesktopPane.add(minador);
        try {
            minador.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Escritorio.class.getName()).log(Level.SEVERE, null, ex);
        }
        minador.setVisible(true);
        
    }//GEN-LAST:event_jButtonMinadorActionPerformed

    private void jButtonCochinillaAereaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCochinillaAereaActionPerformed
        
        CochinillaAerea ca = new CochinillaAerea();
        jDesktopPane.add(ca);
        try {
            ca.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Escritorio.class.getName()).log(Level.SEVERE, null, ex);
        }
        ca.setVisible(true);
        
    }//GEN-LAST:event_jButtonCochinillaAereaActionPerformed

    private void jButtonGallinaCiegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGallinaCiegaActionPerformed
        
        GallinaCiega g = new GallinaCiega();
        jDesktopPane.add(g);
        try {
            g.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Escritorio.class.getName()).log(Level.SEVERE, null, ex);
        }
        g.setVisible(true);
        
    }//GEN-LAST:event_jButtonGallinaCiegaActionPerformed

    private void jButtonBarrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBarrenadorActionPerformed
        
        Barrenador b = new Barrenador();
        jDesktopPane.add(b);
        try {
            b.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Escritorio.class.getName()).log(Level.SEVERE, null, ex);
        }
        b.setVisible(true);
        
    }//GEN-LAST:event_jButtonBarrenadorActionPerformed

    private void jButtonGrilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGrilloActionPerformed
        
        Grillo g = new Grillo();
        jDesktopPane.add(g);
        try {
            g.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Escritorio.class.getName()).log(Level.SEVERE, null, ex);
        }
        g.setVisible(true);
        
    }//GEN-LAST:event_jButtonGrilloActionPerformed

    public void moverPanel(){
        int posicion = this.jPanelOpciones.getX();
        if(posicion > -1){
            Animacion.Animacion.mover_izquierda(0,-430, 2, 2, jPanelOpciones);
        }else {
            Animacion.Animacion.mover_derecha(-430, 0, 2, 2, jPanelOpciones);
        }
    }
    
    public void moverPlagas(){
        int posicionBroca = this.jButtonBroca.getX();
        if(posicionBroca > -1){
            Animacion.Animacion.mover_izquierda(100,-430, 2, 2, jButtonBroca);
        }else {
            Animacion.Animacion.mover_derecha(-430, 100, 2, 2, jButtonBroca);
        }
        
        int posicionCochAerea = this.jButtonCochinillaAerea.getX();
        if(posicionCochAerea > -1){
            Animacion.Animacion.mover_izquierda(100,-430, 2, 2, jButtonCochinillaAerea);
        }else {
            Animacion.Animacion.mover_derecha(-430, 100, 2, 2, jButtonCochinillaAerea);
        }
        
        int posicionBarrenador = this.jButtonBarrenador.getX();
        if(posicionBarrenador > -1){
            Animacion.Animacion.mover_izquierda(100,-430, 2, 2, jButtonBarrenador);
        }else {
            Animacion.Animacion.mover_derecha(-430, 100, 2, 2, jButtonBarrenador);
        }
        
        int posicionMinador = this.jButtonMinador.getX();
        if(posicionMinador > -1){
            Animacion.Animacion.mover_izquierda(520,-430, 2, 2, jButtonMinador);
        }else {
            Animacion.Animacion.mover_derecha(-430, 520, 2, 2, jButtonMinador);
        }
        
        int posicionGallina = this.jButtonGallinaCiega.getX();
        if(posicionGallina > -1){
            Animacion.Animacion.mover_izquierda(520,-430, 2, 2, jButtonGallinaCiega);
        }else {
            Animacion.Animacion.mover_derecha(-430, 520, 2, 2, jButtonGallinaCiega);
        }
        
        int posicionGrillo = this.jButtonGrillo.getX();
        if(posicionGrillo > -1){
            Animacion.Animacion.mover_izquierda(520,-430, 2, 2, jButtonGrillo);
        }else {
            Animacion.Animacion.mover_derecha(-430, 520, 2, 2, jButtonGrillo);
        }
        
        int posicionCochinillaRaiz = this.jButtonCochinillaRaiz.getX();
        if(posicionCochinillaRaiz > -1){
            Animacion.Animacion.mover_izquierda(940,-430, 2, 2, jButtonCochinillaRaiz);
        }else {
            Animacion.Animacion.mover_derecha(-430, 940, 2, 2, jButtonCochinillaRaiz);
        }
        
        int posicionArañaRoja = this.jButtonArañaRoja.getX();
        if(posicionArañaRoja > -1){
            Animacion.Animacion.mover_izquierda(940,-430, 2, 2, jButtonArañaRoja);
        }else {
            Animacion.Animacion.mover_derecha(-430, 940, 2, 2, jButtonArañaRoja);
        }
        
        int posicionPulgones = this.jButtonPulgones.getX();
        if(posicionPulgones > -1){
            Animacion.Animacion.mover_izquierda(940,-430, 2, 2, jButtonPulgones);
        }else {
            Animacion.Animacion.mover_derecha(-430, 940, 2, 2, jButtonPulgones);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escritorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro ButtonAboutUs;
    private rsbuttom.RSButtonMetro ButtonDiagnosticar;
    private rsbuttom.RSButtonMetro ButtonPlagas;
    private rsbuttom.RSButtonMetro ButtonSalir;
    private javax.swing.JButton jButtonArañaRoja;
    private javax.swing.JButton jButtonBarrenador;
    private javax.swing.JButton jButtonBroca;
    private javax.swing.JButton jButtonCochinillaAerea;
    private javax.swing.JButton jButtonCochinillaRaiz;
    private javax.swing.JButton jButtonGallinaCiega;
    private javax.swing.JButton jButtonGrillo;
    private rsbuttom.RSButtonMetro jButtonMenu;
    private javax.swing.JButton jButtonMinador;
    private javax.swing.JButton jButtonPulgones;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelCabecera;
    private javax.swing.JPanel jPanelOpciones;
    // End of variables declaration//GEN-END:variables
}
